### ISSUE TITLE
Question: is this shard designed to work in Linux only?

### ISSUE THREAD

**Issue by kukula** [robacarp/keimeno#2]
Demos don't really clear screan in MacOS

**Comment by robacarp** [comment]
@kukula I developed it on MacOS actually -- the tools I've built with it work fine, but it's possible the demo is bitrotted or incomplete in that respect.  

One published tool I've built for my own use with Keimeno I just call [Place](https://github.com/robacarp/place) is probably the best published example of some simple workflow tooling around Keimeno. It's not perfect but it made short work of some real tedious file management.

**Comment by kukula** [comment]
Thank you @robacarp 
Places project is a good demonstration of Keimeno.
